#Expyriment 0.9.0 (Python 3.6.5), .xpe-file, coding: ISO8859-1
#date: Tue Sep 04 2018 10:39:12
#sha1: None
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Linux', node='L3460', release='4.15.0-33-generic', version='#36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018', machine='x86_64', processor='x86_64')
Time,Type,Event,Value,Detail,Detail2
833,design,log,
#design: #exp: MATH
#design: block_cnt,block_id,trial_cnt,trial_id
833,design,logged,
833,Experiment,started
860,Stimulus,presented,1
871,Stimulus,presented,1
881,Stimulus,presented,1
886,Stimulus,presented,2
1400,TextInput,entered,b''
1439,Stimulus,presented,2
11441,Stimulus,presented,0
21442,stdout,received,'0'
21442,stdout,received,"[4, 'x', 4, '-', 1]"
21442,stdout,received,"[4, 'x', 4, '-', 1]"
21442,stdout,received,'15'
21442,stdout,received,"[[4, 'x', 4, '-', 1], 15]"
21447,Stimulus,presented,0
22231,stderr,received,'Traceback (most recent call last):'
22231,stderr,received,'  File "run_t2-L1.py", line 29, in <module>'
22231,stderr,received,'    Matrix=start.startTrial(NUMBER,OPERATOR) #stim 1 to stim n-1'
22231,stderr,received,'  File "/home/k/workbench/cognitionExp/step2_test_Design/t2_arithmetic_LEVEL1/startTrial.py", line 58, in startTrial'
22231,stderr,received,'    print("ttt %d"%tx1)'
22231,stderr,received,"NameError: name 'tx1' is not defined"
