#Expyriment 0.9.0 (Python 3.6.6), .xpe-file, coding: ISO8859-1
#date: Sat Aug 25 2018 16:34:31
#sha1: None
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Linux', node='L3460', release='4.15.0-33-generic', version='#36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018', machine='x86_64', processor='x86_64')
Time,Type,Event,Value,Detail,Detail2
421,stderr,received,'Traceback (most recent call last):'
421,stderr,received,'  File "run_t1.py", line 24, in <module>'
421,stderr,received,'    COLORS=nbh.n1back(rCOLORS) #fn call'
421,stderr,received,'  File "/home/k/workbench/cognitionExp/step2_test_Design/t1_functions.py", line 43, in n1back'
421,stderr,received,'    m1,m2=random.choice(C),random.choice(C)'
422,stderr,received,"NameError: name 'random' is not defined"
