#Expyriment 0.9.0 (Python 3.6.6), .xpe-file, coding: ISO8859-1
#date: Tue Aug 14 2018 09:47:54
#sha1: None
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Linux', node='L3460', release='4.4.0-109-generic', version='#132~14.04.1-Ubuntu SMP Tue Jan 9 21:46:42 UTC 2018', machine='x86_64', processor='x86_64')
Time,Type,Event,Value,Detail,Detail2
259,stdout,received,'LEVEL 1'
260,stderr,received,'Traceback (most recent call last):'
260,stderr,received,'  File "arithmatictask_v0.py", line 36, in <module>'
260,stderr,received,'    t.add_stimulus(s)'
260,stderr,received,"NameError: name 's' is not defined"
