#Expyriment 0.9.0 (Python 3.6.6), .xpe-file, coding: ISO8859-1
#date: Tue Aug 14 2018 09:34:45
#sha1: None
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Linux', node='L3460', release='4.4.0-109-generic', version='#132~14.04.1-Ubuntu SMP Tue Jan 9 21:46:42 UTC 2018', machine='x86_64', processor='x86_64')
Time,Type,Event,Value,Detail,Detail2
266,stdout,received,'LEVEL 1'
4272,stdout,received,'Block None: LEVEL 1\n    block factors: LEVEL = LEVEL 1\n    n trials: 10\n    trial IDs = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n    trial factors: '
7902,design,log,
#design: #exp: Arithmatic test
#design: block_cnt,block_id,block_LEVEL,trial_cnt,trial_id
#design: 0,0,LEVEL 1,0,0
#design: 0,0,LEVEL 1,1,1
#design: 0,0,LEVEL 1,2,2
#design: 0,0,LEVEL 1,3,3
#design: 0,0,LEVEL 1,4,4
#design: 0,0,LEVEL 1,5,5
#design: 0,0,LEVEL 1,6,6
#design: 0,0,LEVEL 1,7,7
#design: 0,0,LEVEL 1,8,8
#design: 0,0,LEVEL 1,9,9
7903,design,logged,
7903,Experiment,started
8903,Stimulus,presented,1
9904,Stimulus,presented,1
10905,Stimulus,presented,3
11906,Stimulus,presented,3
12907,Stimulus,presented,5
13908,Stimulus,presented,5
14909,Stimulus,presented,7
15910,Stimulus,presented,7
16911,Stimulus,presented,9
17912,Stimulus,presented,9
17913,stdout,received,'LEVEL 2'
21920,stdout,received,'Block None: LEVEL 2\n    block factors: LEVEL = LEVEL 2\n    n trials: 10\n    trial IDs = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n    trial factors: '
21920,stderr,received,'Traceback (most recent call last):'
21920,stderr,received,'  File "arithmatictask_v0.py", line 49, in <module>'
21920,stderr,received,'    control.start()'
21920,stderr,received,'  File "/home/k/workbench/cognitionExp/lib/python3.6/site-packages/expyriment/control/_experiment_control.py", line 73, in start'
21933,stderr,received,'    raise Exception("Experiment is already started!")'
21933,stderr,received,'Exception: Experiment is already started!'
