#Expyriment 0.9.0 (Python 3.6.6), .xpe-file, coding: ISO8859-1
#date: Mon Aug 13 2018 20:17:50
#sha1: None
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Linux', node='L3460', release='4.4.0-109-generic', version='#132~14.04.1-Ubuntu SMP Tue Jan 9 21:46:42 UTC 2018', machine='x86_64', processor='x86_64')
Time,Type,Event,Value,Detail,Detail2
272,stderr,received,'Traceback (most recent call last):'
272,stderr,received,'  File "nbacktask_copy.py", line 80, in <module>'
273,stderr,received,'    for  cnt,trial in enumerate(blocks.trials):'
273,stderr,received,"NameError: name 'blocks' is not defined"
